spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ttt
    username: postgres
    password: login456456
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

#server:
#  error:
#    include-stacktrace: on_param